// Custom next/image loader for static export (no Image Optimization server
// at runtime). Variants are pre-generated by scripts/optimize-images.mjs at
// fixed widths per image; this snaps any requested width up to the nearest
// available pre-generated file instead of assuming an on-demand resizer.
type LoaderArgs = { src: string; width: number };

const AVAILABLE_WIDTHS: Record<string, number[]> = {
  hero: [640, 960, 1280, 1920],
  "card-kids": [400, 600, 800],
  "card-youth": [400, 600, 800],
  "card-adults": [400, 600, 800],
};

export default function imageLoader({ src, width }: LoaderArgs): string {
  const match = src.match(/^\/images\/([a-z-]+)\.(avif|webp)$/);
  if (!match) return src;
  const [, name, format] = match;
  const widths = AVAILABLE_WIDTHS[name];
  if (!widths) return src;
  const chosen = widths.find((w) => w >= width) ?? widths[widths.length - 1];
  return `/images/${name}-${chosen}.${format}`;
}
